apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed
  labels:
    app: udagram-api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-api-feed
  template:
    metadata:
      labels:
        app: udagram-api-feed
    spec:
      containers:
      - name: udagram-api-feed
        image: ucheg6/udagram-api-feed:v1
        envFrom: 
          - configMapRef:
              name: udagram-env
          - secretRef:
              name: udagram-secrets
          - secretRef:
              name: udagram-aws-secrets 
              